#!/bin/bash


function dkr-lvms() {
	sudo systemctl stop docker.service

	sudo lvremove /dev/docker-vg/docker-pool
	sudo vgremove docker-vg
	sudo pvremove /dev/xvdf1
	sudo rm -rf /var/lib/docker

	# Backup files
	sudo cp /etc/sysconfig/docker-storage-setup /etc/sysconfig/docker-storage-setup.rpmsave
	sudo cp /etc/sysconfig/docker-storage /etc/sysconfig/docker-storage.rpmsave

	# Remove original
	sudo rm -rf /etc/sysconfig/docker-storage
	sudo rm -rf /etc/sysconfig/docker-storage-setup

cat <<EOF >> /etc/sysconfig/docker-storage-setup
	WIPE_SIGNATURES=true
	DEVS=/dev/xvdf
	VG=docker-vg
EOF

	sudo mkfs.ext3 /dev/xvdf
	sudo docker-storage-setup
}

function dkr-vols() {
	find '/var/lib/docker/volumes/' -mindepth 1 -maxdepth 1 -type d | grep -vFf <(
	  docker ps -aq | xargs docker inspect | jq -r '.[]|.Mounts|.[]|.Name|select(.)'
	)
}

function krp-pull() {
	hosts=( 192.168.0.251 192.168.0.201 192.168.0.202 192.168.0.203 192.168.0.204 )

	for h in "${hosts[@]}"; do
	  ssh -f $h "sh -c 'nohup docker pull registry.access.redhat.com/jboss-eap-6/eap64-openshift:1.1 > /dev/null 2>&1 &'"
	  ssh -f $h "sh -c 'nohup docker pull kubernetes/guestbook > /dev/null 2>&1 &'"
	  ssh -f $h "sh -c 'nohup docker pull registry.access.redhat.com/openshift3/mongodb-24-rhel7 > /dev/null 2>&1 &'"
	  ssh -f $h "sh -c 'nohup docker pull registry.access.redhat.com/rhscl/php-56-rhel7 > /dev/null 2>&1 &'"
	done
}


function resize-docker-lv() {
	LV_NAME=
	VG_NAME=
	LV_SIZE=10G

	lvreduce -r -L -${LV_SIZE} /dev/${VG_NAME}/${LV_NAME}

cat <<EOF >> /etc/sysconfig/docker-storage-setup
VG=${VG_NAME}
EOF

	docker-storage-setup

	lvextend -l +100%FREE /dev/${VG_NAME}/${LV_NAME}
}
