#!/bin/bash

TMP_DIR=$(mktemp --suffix oc-cli -d)
OC_HOME=/usr/bin
ARCHIVE=$HOME/Downloads/openshift-origin-client-tools-v1.5.1-7b451fc-linux-64bit.tar.gz

# Check if archive exists
[[ ! -f $ARCHIVE ]] && echo "Archive not found" && exit 1

# Extract tarball
tar -xzf $ARCHIVE -C $TMP_DIR --strip 1 &>/dev/null

# Add execution file mode
chmod +x $TMP_DIR/oc

# Install and create bash completion drop-in
echo -n "root@$HOSTNAME "; su - root -c "cp -f $TMP_DIR/oc $OC_HOME
                                         oc completion bash > /etc/bash_completion.d/oc.sh
                                         source /etc/bash_completion.d/oc.sh"

# Source system wide initialization file
source /etc/bashrc

# Remove existing connection profile(s)
[[ -d $HOME/.kube ]] && rm -rf $HOME/.kube

# Test version subcommand
oc version
