#!/bin/bash
epel=$1

# Get the most current version of all packages.
sudo yum clean all
sudo rm -rf /var/cache/yum/*
sudo yum makecache fast

if [ ${epel:-0} -eq 0 ]; then
  sudo yum -y update
else
  sudo yum -y update --enablerepo=epel
fi

sudo yum -y autoremove

# sudo dnf clean all
# sudo rm -rf /var/cache/dnf/*
# sudo dnf makecache
#
# if [[ ${epel} == "" ]]; then
#   sudo dnf -y update
# else
#   sudo dnf -y update --enablerepo=epel
# fi
#
# sudo dnf -y autoremove

# function epel() {
# 	# Install EPEL packages (Ansible)
# 	pushd /tmp
# 	sudo wget https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
# 	sudo yum -y install ./epel-release-latest-7.noarch.rpm
# 	popd
#
# 	# Clean temp folder contents.
# 	sudo rm -rf /tmp/*
#
# 	# Disable EPEL packages (default).
# 	sudo yum-config-manager --disable epel
#
# 	# Get the most current version of all packages.
# 	sudo yum-clean-update
# }
